// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Junior_20190009.DAL;

namespace P2_AP1_Junior_20190009.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Junior_20190009.Entidades.Proyectos", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionProyecto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("P2_AP1_Junior_20190009.Entidades.ProyectosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimentos")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("DetalleId");

                    b.HasIndex("TipoId");

                    b.ToTable("ProyectosDetalle");
                });

            modelBuilder.Entity("P2_AP1_Junior_20190009.Entidades.Tareas", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaTarea")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TareaId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            TareaId = 1,
                            FechaTarea = new DateTime(2021, 11, 8, 17, 16, 48, 400, DateTimeKind.Local).AddTicks(823),
                            Tiempo = 0,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TareaId = 2,
                            FechaTarea = new DateTime(2021, 11, 8, 17, 16, 48, 400, DateTimeKind.Local).AddTicks(9871),
                            Tiempo = 0,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TareaId = 3,
                            FechaTarea = new DateTime(2021, 11, 8, 17, 16, 48, 400, DateTimeKind.Local).AddTicks(9883),
                            Tiempo = 0,
                            TipoTarea = "Programación"
                        },
                        new
                        {
                            TareaId = 4,
                            FechaTarea = new DateTime(2021, 11, 8, 17, 16, 48, 400, DateTimeKind.Local).AddTicks(9885),
                            Tiempo = 0,
                            TipoTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("P2_AP1_Junior_20190009.Entidades.TareasDetalle", b =>
                {
                    b.Property<int>("TareaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TareaId");

                    b.ToTable("TareasDetalle");
                });

            modelBuilder.Entity("P2_AP1_Junior_20190009.Entidades.ProyectosDetalle", b =>
                {
                    b.HasOne("P2_AP1_Junior_20190009.Entidades.Proyectos", null)
                        .WithMany("Detalle")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P2_AP1_Junior_20190009.Entidades.TareasDetalle", b =>
                {
                    b.HasOne("P2_AP1_Junior_20190009.Entidades.Tareas", null)
                        .WithMany("Detalle")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P2_AP1_Junior_20190009.Entidades.Proyectos", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("P2_AP1_Junior_20190009.Entidades.Tareas", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
